language: java
jdk:
  - openjdk7
  - oraclejdk7  
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'EmailSignatureApp' ]; then cd .. && eval "mv $currentfolder EmailSignatureApp" && cd EmailSignatureApp; fi
  - npm install -g bower grunt-cli grunt
  - bower install && npm install && grunt
